package huard.iws.db;

import huard.iws.model.AListColumnInstruction;

import org.springframework.jdbc.core.simple.ParameterizedRowMapper;

public interface ListColumnInstructionDao {

	public AListColumnInstruction getListColumnInstruction(int id);

	public AListColumnInstruction getListColumnInstruction(int id, int listId);

	public void updateListColumnInstruction(AListColumnInstruction aListColumnInstruction);

	public void updateListColumnInstruction(AListColumnInstruction aListColumnInstruction, int parentListId);

	public void insertListColumnInstruction(AListColumnInstruction aListColumnInstruction, boolean autoGenerated);

	public void insertListColumnDesign(AListColumnInstruction aListColumnInstruction);

	/*public void replaceListColumnInstruction(AListColumnInstruction aListColumnInstruction);*/

	public void deleteListColumnInstruction(int id);

	public void deleteListColumnDesign(int columnInstructionId, int listId);

	public ParameterizedRowMapper<AListColumnInstruction> getRowMapper();

}
